#!/usr/bin/env bash
input="$1"

# detekt output /absolute/path/file:123:1
if [[ $input =~ (.*):([0-9]+):([0-9]+): ]]; then
  file_path="${BASH_REMATCH[1]}"
  line_number="${BASH_REMATCH[2]}"
  column="${BASH_REMATCH[3]}"
  encoded_path=$(echo "$file_path" | sed 's/ /%20/g')
  open "idea://open?file=$encoded_path&line=$line_number&column=$column"
else
  echo "Error: Dunno how to open, could not parse the input, got: $input"
  exit 1
fi
