#!/bin/sh
# latest homebrew
ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
brew update

# upgrade
brew upgrade
brew upgrade brew-cask
brew cleanup
brew cask cleanup

# stuff
brew install ag
brew install coreutils # os x ones are outdated
brew install findutils
brew install bash # bash 4
brew install git
brew install gifsicle
brew install ctags-exuberant
#brew install macvim --override-system-vim --with-python3
brew install emacs --with-cocoa --with-ctags --with-gnutls --with-imagemagick --with-librsvg

brew install markdown
brew install jq # cmd line json parsing
#brew install mackup # backup config for brew installed stuff
#brew install maven
#brew install mongodb
brew install siege
brew install ngrep
brew install pcre
brew install phantomjs
brew install gnupg
#brew install redis
brew install sbt
#brew install scala
brew install tmux
brew install reattach-to-user-namespace # tmux os x clipboard support
brew install tree
brew install webkit2png
brew install wget
brew install unrar

# https://github.com/caskroom/homebrew-cask
brew install caskroom/cask/brew-cask

# applications
brew cask install alfred
brew cask install chromecast
brew cask install dash
#brew cask install atom
brew cask install dropbox
#brew cask install gitx-rowanj
brew cask install google-chrome
brew cask install iterm2
brew cask install slack
brew cask install spotify
#brew cask install vagrant
#brew cask install virtualbox
#brew cask install intellij-idea
#brew cask install robomongo
brew cask install send-to-kindle

# show cask installs in alfred
brew cask alfred link

# quick look plugins - https://github.com/sindresorhus/quick-look-plugins
brew cask install qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzipql qlimagesize webpquicklook suspicious-package

brew tap homebrew/dupes
brew install homebrew/dupes/grep # os x ones are outdated

# remove tmp files
brew cleanup
brew cask cleanup
