#!/bin/sh
# latest homebrew
#/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
# brew update

# upgrade
brew upgrade
brew cleanup

# stuff
brew install --cask 1password/tap/1password-cli
brew install --cask temurin
brew install --cask temurin17
brew install rg
brew install pyenv
brew install gh
brew install borkdude/brew/babashka
brew install babashka/brew/obb # cljs scripting, like babashka
brew install coreutils # os x ones are outdated
#brew install findutils
#brew install bash # bash 4
brew install grip
brew install git
brew install gifsicle
brew install neovim
#brew install boot-clj
brew tap d12frosted/emacs-plus
brew install emacs-plus@28 --with-modern-black-variant-icon
#brew install homebrew/emacs/w3
brew install jq # cmd line json parsing
brew install glances
brew install gnupg
brew install tmux
brew install tree
brew install watch
brew install hashicorp/tap/terraform-ls # terraform lsp
brew install webkit2png
brew install wget
brew install unrar

# gradlewrapperwrapper gw
brew tap gdubw/gng
brew install gng

#brew install redis
#brew install ffmpeg
#brew install ctags
#brew install ctags-exuberant
#brew install markdown
#brew install pup
#brew install maven
#brew install siege
#brew install ngrep
#brew install pcre
#brew install sbt
#brew install tfenv # terraform
#brew install tgenv # terragrunt
#brew install reattach-to-user-namespace # tmux os x clipboard support
#brew install source-highlight

brew install koekeishiya/formulae/yabai
brew services start yabai
brew install koekeishiya/formulae/skhd
brew services start skhd
brew install --cask easy-move-plus-resize # and bring back cmd + mouse to move and resize windows

# https://github.com/caskroom/homebrew-cask
brew tap homebrew/cask

# applications
brew install --cask alfred
brew install --cask dash
brew install --cask dropbox
brew install --cask firefox
brew install --cask google-chrome
brew install --cask google-cloud-sdk
brew install --cask iterm2
brew install --cask intellij
brew install --cask spotify
#brew install --cask rectangle # try yabai+skhd instead
#brew cask install mactex
#brew cask install slack
#brew cask install send-to-kindle

# quick look plugins - https://github.com/sindresorhus/quick-look-plugins
#brew cask install qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzipql qlimagesize webpquicklook suspicious-package

#brew tap homebrew/dupes
#brew install homebrew/dupes/grep # os x ones are outdated

# remove tmp files
brew cleanup
brew cask cleanup
