#!/usr/bin/env bash
# details in available commands
# https://github.com/koekeishiya/yabai/blob/master/src/message.c
#
# yabai -m query --windows | jq '.[].app'
# yabai -m query --windows | jq '.[] | select(.app == "iTerm2") | .title'

# DO NOT add defaults to manage=on for whole apps in this file, it borks
# popups/hovers e.g. in Chrome , as it will force yabai to handle these windows
# as well. Layout bsp will suffice to make yabai default to tile window for apps.

# buggy on yabai with alacritty 0.13.1, force it
yabai -m rule --add app="^Alacritty$" manage=on

yabai -m rule --add title="Info$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Install" manage=off
yabai -m rule --add app="^Dictionary" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System" manage=off
yabai -m rule --add app="^Problem Report" manage=off

yabai -m rule --add app="^Microsoft Teams" manage=off               # Teams
yabai -m rule --add app="^Microsoft" title="Reminders?$" manage=off # n Reminder[s]
# TODO does this fix all popup windows?
#yabai -m rule --add app="^Microsoft" subrole=AXStandardWindow manage=off

yabai -m rule --add app="IntelliJ IDEA" title="^Code with me" manage=off
yabai -m rule --add app="IntelliJ IDEA" title="^Convert Code" manage=off
yabai -m rule --add app="IntelliJ IDEA" title="^(Copy|Add) Code" manage=off
# TODO does this fix all popup windows?
#yabai -m rule --add app="IntelliJ IDEA" subrole=AXStandardWindow manage=off

yabai -m rule --add app="Sonos S1 Controller" manage=off

yabai -m rule --add app="^Google Chrome$" title="^Picture in Picture$" manage=off layer=above

# show digital colour meter topmost and on all spaces
# sticky doesnt work without more liberal yabai scripting than you enabled..
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on layer=above manage=off

yabai -m rule --add title="1Password$" manage=off layer=above
yabai -m rule --add title="^Settings$" manage=off layer=above

# make space switching work without disabling sip
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse off

#yabai -m config window_shadow float
yabai -m config window_shadow off

# move and resize with mouse
# TODO interferes with opt+click in macos menubar
#yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# set layout
yabai -m config layout bsp

# floating windows are topmost, new right, botton
yabai -m config window_placement second_child

yabai -m config top_padding 3
yabai -m config right_padding 3
yabai -m config bottom_padding 3
yabai -m config left_padding 3
yabai -m config window_gap 3
