# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap-default.toml

[[mgr.prepend_keymap]]
on = "?"
run = "help"
desc = ""

[[mgr.prepend_keymap]]
on = "<A-Up>"
run = "cd .."
desc = ""

[[mgr.prepend_keymap]]
on = "<A-Down>"
run = "enter"
desc = ""

[[mgr.prepend_keymap]]
on = "<C-h>"
run = "hidden toggle"
desc = ""

[[mgr.prepend_keymap]]
on = "<C-Right>"
run = "tag_switch -1 --relative"
desc = ""

[[mgr.prepend_keymap]]
on = "<C-Left>"
run = "tag_switch 1 --relative"
desc = ""

[[mgr.prepend_keymap]]
on = "e"
run = 'shell -- emacsclient --no-wait "$@"'
desc = ""

[[mgr.prepend_keymap]]
on = ["g", "e"]
run = 'shell --block -- emacsclient --no-wait "$@"'
desc = ""

[[mgr.prepend_keymap]]
on = ["g", "E"]
run = 'shell --block -- emacsclient -t "$@"'
desc = ""

[[mgr.prepend_keymap]]
on = ["g", "v"]
run = 'shell --block -- vim "$@"'
desc = ""

[[mgr.prepend_keymap]]
on = ["g", "o"]
run = 'shell -- thunar "$@"'
desc = ""

[[mgr.prepend_keymap]]
on = ["g", "t"]
run = 'shell --block -- ghostty --working-directory="$@"'
desc = "spawn terminal"

[[mgr.prepend_keymap]]
on = ["g", "T"]
run = ['shell -- ghostty --working-directory="$@"']
desc = "spawn terminal"
orphan = true

# Remap ; to blocking interactive shell (what : used to do)
[[mgr.prepend_keymap]]
on = [ ";" ]
run = "shell --interactive --block"
desc = "Shell (block)"

# Now use : for vim-style commands
[[mgr.prepend_keymap]]
on = [ ":", "q" ]
run = "quit"
desc = "Quit (vim-style)"
