# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/yazi-default.toml
[mgr]
# . or c-h
show_hidden = false
cursor_blink = true

[[opener.edit]]
run = 'emacsclient --socket-name $HOME/.emacs.d/server/server -n -q -a "" "$@"'
desc = "$EDITOR"
