#!/bin/bash
# ls
alias ls="exa --group-directories-first"
alias l="exa -a --group-directories-first"
alias la="exa -1 -a --tree -L 1 --classify --group --group-directories-first"
alias ll="exa -l -a --classify --group --group-directories-first"
alias lal="exa -l -a --classify --group --group-directories-first"

alias lt="exa -1 --group --classify --tree -L 1 --group-directories-first"
alias ltt="exa -1 --group --classify --tree -L 2 --group-directories-first"
alias lttt="exa -1 --group --classify --tree -L 3 --group-directories-first"

alias lat="exa -l -1 -a --group --classify --tree -L 1 --group-directories-first"
alias latt="exa -l -1 -a --group --classify --tree -L 2 --group-directories-first"
alias lattt="exa -l -1 -a --group --classify --tree -L 3 --group-directories-first"
# alias lla="exa -l --all --group --classify"
# alias lal="exa -l --all --group --classify"

alias grep="grep --color=always"

# local ip
alias whatsmyip="dig +short myip.opendns.com @resolver1.opendns.com"

# recursively delete annoying files
alias cleanup-dsstore="find . -name '*.DS_Store' -type f -ls -delete"
alias cleanup-nodemodules="find . -name 'node_modules' -type d -prune -print -exec rm -rf '{}' \;"

# http
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""
# @janmoesen’s protip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
    alias "$method"="lwp-request -m '$method'"
done

if [[ -n "$INSIDE_EMACS" ]]; then
    alias clear='vterm_printf "51;Evterm-clear-scrollback";tput clear'
fi

case $(uname) in
    Darwin)
        # empty all the Trash
        alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; rm -rfv ~/.Trash"

        # hide/show all desktop icons (useful when presenting)
        alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
        alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

        # hide/show hidden files
        alias hidehidden="defaults write com.apple.finder AppleShowAllFiles -boolean false && killall Finder"
        alias showhidden="defaults write com.apple.finder AppleShowAllFiles -boolean true && killall Finder"

        alias flushyosemitedns="sudo discoveryutil mdnsflushcache;sudo discoveryutil udnsflushcaches"

        # logout os x
        alias lout="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
        ;;
esac

# wait for internet connection
alias waitforinternet='while true; do ping -c 1 -t 2 nrk.no && say "gotz internet" && date && break; sleep 2; done'

# restart a hanging os x touch bar
alias killtouchbar="sudo pkill TouchBarServer; sudo killall ControlStrip"

# run local module from node_modules/bin
alias npm-exec='PATH=$(npm bin):$PATH'

# kill emacs daemon
alias emdkillhard="ps x | ack 'Emacs\ (-nw\ )?--daemon' | awk '{print \$1}' | xargs kill"
alias emdkill="emacsclient -e '(kill-emacs)'"

# macvim vim
alias vim='nvim'

# git add remote for prs
alias gadd-origin-pr='git config --add remote.origin.fetch \"+refs/pull/*/head:refs/remotes/origin/pr/*\"'

# go to git root
alias gr='cd $(git rev-parse --show-toplevel)'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias t='exa --tree --level 1'
alias tt='exa --tree --level 2'
alias ttt='exa --tree --level 3'
alias tttt='exa --tree --level 4'

# less
#alias less='less -m -N -g -i -J --underline-special --SILENT'

# gdate can do more, e.g.
# gdate -u -d '-10 min' +%Y-%m-%dT%H:%M:%SZ
alias isodate="date +'%Y-%m-%dT%H:%M:%SZ'"

alias latest-changes="find . -type f -printf '%T@ %p\n' | sort -k1,1nr | head -10"

alias yabai-restart="brew services restart yabai"
alias yabai-window-name="while true; do yabai -m query --windows --window | jq \"(.title), (.role), (.subrole)\"; sleep 1; done"

alias jq-paths="jq -c 'path(..)|[.[]|tostring]|join(\"/\")'"

# Uses full path to ghostscript, conflicts with gs() magitgit status for vterm
alias merge-pdfs="/usr/local/bin/gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=merged.pdf *.pdf"

alias brew-list-installed="brew list | xargs brew desc --eval-all"

alias gcloud-set-project="gcloud config set project"
alias gcloud-get-project="gcloud config get project"
alias gcloud-describe-role="gcloud iam roles describe"
alias sourcegauth="source $HOME/Code/gauth/gauth.sh"
alias tg="terragrunt"

# -i turns on the itemized format, which shows more information than the default format
# -b makes rsync backup files that exist in both folders, appending ~ to the old file. You can control this suffix with --suffix .suf
# -u makes rsync transfer skip files which are newer in dest than in src
# -z turns on compression, which is useful when transferring easily-compressible files over slow links
# -P turns on --partial and --progress
# --partial makes rsync keep partially transferred files if the transfer is interrupted
# --progress shows a progress bar for each transfer, useful if you transfer big files
alias sync-dirs="rsync -abviuzP"

# https://stribika.github.io/2015/01/04/secure-secure-shell.html
alias generate-ssh-key="ssh-keygen -t rsa -b 4096 -o -a 100"

# preview formatted xml, e.g. with xmlformat *.xml | less
alias xmlformat="xmllint --format"

# kill gpg agent
alias kill-gpg-agent="killall gpg-agent && gpg-connect-agent reloadagent /bye"

case $(uname) in
    Linux)
        alias reload-xresources=xrdb -merge ~/Xresources

        alias bios="systemctl reboot --firmware-setup"
        # dont use grun/win any longer
        #alias rebootwin="sudo grub-reboot 2 && sudo reboot"

        # open ports
        alias ports="sudo lsof -i -P -n | rg -i listen"

        # nix
        alias rebuild-switch-torgnix="pushd ~/nixos-config; sudo nixos-rebuild --flake .#torgnix switch; popd"
        ;;
    Darwin)
        alias ports="sudo lsof -i -n -P | rg -i tcp | rg -i listen"
        ;;
esac

# git
alias git-remove-merged-branches="git branch --merged main | grep -v '^[ *]*main$' | xargs -r git branch -d"

alias kill-gradle-processes="ps x | grep gradle | grep -v 'grep.*gradle' | awk '{print $1}' | xargs kill"
