#!/bin/bash
# ls
case $(uname) in
  Linux)
    alias l="ls -GF --color"
    alias ll="ls -laGFh --color"
    alias la="ls -laGFh --color"
    ;;
  Darwin)
    alias l="ls -GF"
    alias ll="ls -laGFh"
    alias la="ls -laGFh"
    ;;
esac
alias grep="grep --color=always"
#alias ls="ls -GF --color"

# local ip
alias whatsmyip="dig +short myip.opendns.com @resolver1.opendns.com"

# recursively delete annoying files
alias cleanup-dsstore="find . -name '*.DS_Store' -type f -ls -delete"
alias cleanup-nodemodules="find . -name 'node_modules' -type d -prune -print -exec rm -rf '{}' \;"

# http
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""
# @janmoesen’s protip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
  alias "$method"="lwp-request -m '$method'"
done

# empty all the Trash
alias emptytrash="sudo rm -rfv /Volumes/*/.Trashes; rm -rfv ~/.Trash"

# hide/show all desktop icons (useful when presenting)
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"

# hide/show hidden files
alias hidehidden="defaults write com.apple.finder AppleShowAllFiles -boolean false && killall Finder"
alias showhidden="defaults write com.apple.finder AppleShowAllFiles -boolean true && killall Finder"

alias flushyosemitedns="sudo discoveryutil mdnsflushcache;sudo discoveryutil udnsflushcaches"

# logout os x
alias lout="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

# wait for internet connection
alias waitforinternet='while true; do ping -c 1 -t 2 vg.no && say "we gotz internet" && date && break; sleep 2; done'

# restart a hanging os x touch bar
alias killtouchbar="sudo pkill TouchBarServer; sudo killall ControlStrip"

# run local module from node_modules/bin
alias npm-exec='PATH=$(npm bin):$PATH'

# kill emacs daemon
alias emdkillhard="ps x | ack 'Emacs\ (-nw\ )?--daemon' | awk '{print \$1}' | xargs kill"
alias emdkill="emacsclient -e '(kill-emacs)'"

# macvim vim
alias vim='nvim'

# git add remote for prs
alias gadd-origin-pr='git config --add remote.origin.fetch \"+refs/pull/*/head:refs/remotes/origin/pr/*\"'

# go to git root
alias gr='cd $(git rev-parse --show-toplevel)'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# less
#alias less='less -m -N -g -i -J --underline-special --SILENT'

alias isodate="date +'%Y-%m-%dT%H:%M:%SZ'"

alias latest-changes="find . -type f -printf '%T@ %p\n' | sort -k1,1nr | head -10"

alias yabai-restart="brew services restart yabai"
alias yabai-window-name="while true; do yabai -m query --windows --window | jq .title; sleep 1; done"

alias jq-paths="jq -c 'path(..)|[.[]|tostring]|join(\"/\")'"

# Uses full path to ghostscript, conflicts with gs() magitgit status for vterm
alias merge-pdfs="/usr/local/bin/gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=merged.pdf *.pdf"

alias brew-list-installed="brew list | xargs brew desc --eval-all"

alias gcloud-set-project="gcloud config set project"
alias gcloud-describe-role="gcloud iam roles describe"
alias sourcegauth="source $HOME/Code/gauth/gauth.sh"

# -i turns on the itemized format, which shows more information than the default format
# -b makes rsync backup files that exist in both folders, appending ~ to the old file. You can control this suffix with --suffix .suf
# -u makes rsync transfer skip files which are newer in dest than in src
# -z turns on compression, which is useful when transferring easily-compressible files over slow links
# -P turns on --partial and --progress
# --partial makes rsync keep partially transferred files if the transfer is interrupted
# --progress shows a progress bar for each transfer, useful if you transfer big files
alias sync-dirs="rsync -abviuzP"

# https://stribika.github.io/2015/01/04/secure-secure-shell.html
alias generate-ssh-key="ssh-keygen -t rsa -b 4096 -o -a 100"

case $(uname) in
  Linux)
    # can't live without open . from os x
    alias open=thunar

    alias bios="systemctl reboot --firmware-setup"
    alias rebootwin="sudo grub-reboot 2 && sudo reboot"
    ;;
esac
